### ISSUE TITLE
A connection attempt failed

### ISSUE THREAD

**Issue by hejazia** [AngleSharp/AngleSharp.Io#27]
Hi Florian,

I scarp url using AngleSharp.Io i do this:
`      
 var handler = new HttpClientHandler
        {
             Proxy = new WebProxy($"{proxy?.Address}:{proxy?.Port}",false),
              PreAuthenticate = true,
               UseDefaultCredentials = false,
        };`
` var config = Configuration.Default.WithRequesters(handler).WithTemporaryCookies()
   .WithDefaultLoader(new LoaderOptions { IsResourceLoadingEnabled = true });`

but i get following error :"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
i do this:
` var client = new HttpClient(handler: handler, disposeHandler: true)
        {
               Timeout = TimeSpan.FromMinutes(2)
         };`

but still get the error

**Comment by FlorianRappl** [comment]
Hi @hejazia I think this is rather a misconfiguration of the proxy.

The error points to a connectivity problem. AngleSharp.Io does only talk to the `IRequester` interface, which in your case was set up to use the `HttpClient` from .NET. If a connectivity issue appears its either a misconfiguration or a bug in this class (i.e., .NET itself).

How come you think this is an issue in AngleSharp.Io?

**Comment by hejazia** [comment]
hi @FlorianRappl  actually i am new to `HttpClient `configuration but i follow the document. the proxy work in selenium but as you know it is a bit slow. does the target website block my request or should i edit my httpclient configuration .
p.s. i am using .Net Core Could it be a reason

**Comment by FlorianRappl** [comment]
Alright, what I would recommend is to first try directly with the `HttpClient`. If that does not work then doing it via AngleSharp cannot work, too. If it works with the `HttpClient` directly, but not with AngleSharp then we'd need to look into this.

Once you have the right config you can move on the AngleSharp.

Regarding the target website blocking the request: I doubt it. It would reject it, but since we see a timeout I guess it may either be a network issue or a misconfiguration. Further investigation required.
